# Coffee Palette
# Maintainer: None

# Basic colors
background            #4c3322
foreground            #a86b43

# Cursor
cursor                #c6a5a5
cursor_text_color     #4c3322

# Selection
selection_background  #5A3E2D
selection_foreground  #c6a5a5

# URL color
url_color             #4370ba

# Window border colors
active_border_color   #B08160
inactive_border_color #8c7260
bell_border_color     #f9e2af

# Tab bar
active_tab_background   #B08160
active_tab_foreground   #4c3322
inactive_tab_background #563D2B
inactive_tab_foreground #8c7260

# Marks
mark1_background #4370ba
mark1_foreground #4c3322
mark2_background #cba6f7
mark2_foreground #4c3322
mark3_background #b28463
mark3_foreground #4c3322

# ─── 16 Terminal Colors ──────────────────────────────────────────────────────

# black
color0  #4c3322
color8  #5A3E2D

# red
color1  #bf4459
color9  #f38ba8

# green
color2  #a6e3a1
color10 #a6e3a1

# yellow
color3  #f9e2af
color11 #f9e2af

# blue
color4  #4370ba
color12 #4370ba

# magenta / mauve
color5  #cba6f7
color13 #f5c2e7

# cyan / teal
color6  #94e2d5
color14 #89dceb

# white
color7  #c6a5a5
color15 #a86b43
