#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

# exec-once = $terminal
# exec-once = nm-applet &
# exec-once = waybar & hyprpaper & firefox
exec-once = hyprpaper & waybar -s .config/waybar/mocha/style.css -c .config/waybar/mocha/config.jsonc & nm-applet & swaync
exec = hyprctl setcursor Bibata-Modern-Ice 24
exec = "/usr/bin/kanata -c /home/archibald_baller/.kanata.kbd"
exec-once = systemctl --user start hyprpolkitagent
exec-once = hyprpm reload -n
#exec = hyprpanel
exec-once = hypr-dock
