##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules
# Example windowrule
windowrule {
  name = float
  match:class = org.keepassxc.KeePassXC

  float = on
  size = 800 600

  }

windowrule {
name = typer
match:class = typer

  float = on
  size = 1080 600
  }


windowrule {
name = big_float
match:class = signal 

float = on
size = 1200 900

  }

windowrule {
  name = kando
  match:class = ^(kando)$
  no_blur = on
  opaque = on
  size = 100% 100%
  border_size = 0
  no_anim = on
  float = on
  pin = on
}
